/* llm-export v1.2.0 — extension content script
 * GENERATED by build.mjs from src/. Do not edit this file; edit src/ and rebuild.
 */
/* llm-export — runtime namespace and shared helpers.
 * Concatenated first by build.mjs; everything else hangs off globalThis.LLMExport.
 */
(() => {
  'use strict';

  const NS = globalThis.LLMExport || (globalThis.LLMExport = {});

  NS.version   = '1.2.0';
  NS.providers = NS.providers || [];

  /** Register a site adapter. See src/providers/claude.js for the shape. */
  NS.register = provider => {
    const i = NS.providers.findIndex(p => p.id === provider.id);
    if (i >= 0) NS.providers[i] = provider; else NS.providers.push(provider);
    return provider;
  };

  /** First provider that says it recognises the current page. */
  NS.detect = () => NS.providers.find(p => { try { return p.detect(); } catch (_) { return false; } }) || null;

  NS.util = {
    sleep: ms => new Promise(r => setTimeout(r, ms)),
    qsa: (sel, root = document) => Array.from(root.querySelectorAll(sel)),

    /* strip icon-font private-use glyphs and non-breaking spaces out of button text */
    clean: s => (s || '').replace(/[\uE000-\uF8FF]/g, '').replace(/\u00A0/g, ' ').trim(),

    /* the element that actually scrolls the transcript */
    findScroller(el) {
      let n = el;
      while (n && n !== document.body) {
        const st = getComputedStyle(n);
        if (/(auto|scroll)/.test(st.overflowY) && n.scrollHeight > n.clientHeight + 40) return n;
        n = n.parentElement;
      }
      return document.scrollingElement || document.documentElement;
    },

    tryJson(t) { try { return JSON.parse(t); } catch (_) { return null; } },

    slugify: (s, max = 50) =>
      (s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, max),

    stamp: t => (t ? new Date(t).toISOString().replace('T', ' ').replace(/\.\d+Z$/, 'Z') : ''),

    fileStamp: () => new Date().toISOString().replace(/[:T]/g, '-').slice(0, 16),
  };
})();

/* llm-export — generic DOM to Markdown serialiser.
 * Site-agnostic: providers decide which nodes to hand it.
 */
(() => {
  'use strict';

  const NS = globalThis.LLMExport;
  const { qsa, clean } = NS.util;

  /* Nodes that are chrome, not content. Providers can extend this list. */
  const SKIP = [
    '.sr-only',
    /* Angular Material's screen-reader-only class. Gemini uses it for a
       "You said <first 100 characters>" heading on every user message, which
       otherwise exports as a duplicate of the message it labels. */
    '.cdk-visually-hidden',
    '.visually-hidden',
    '[aria-hidden="true"]',
    '[role="toolbar"]',
    '[data-cds="MessageActions"]',
    '[data-testid="message-actions"]',
    '[data-testid="failed-send-status-region"]',
    '[data-testid="transcript-spacer"]',
    '[data-testid="transcript-trailing"]',
  ];

  const skipSel = () => SKIP.join(', ');
  const isSkippable = n => n.nodeType === 1 && n.matches(skipSel());

  function fence(text, lang) {
    const body = String(text).replace(/\s+$/, '');
    let tick = '```';
    while (body.includes(tick)) tick += '`';
    return '\n' + tick + (lang || '') + '\n' + body + '\n' + tick + '\n\n';
  }

  function ser(node, ctx) {
    if (node.nodeType === 3) {
      return ctx.pre ? node.nodeValue : node.nodeValue.replace(/\s+/g, ' ');
    }
    if (node.nodeType !== 1 || isSkippable(node)) return '';

    const tag  = node.tagName;
    const kids = () => Array.from(node.childNodes).map(n => ser(n, ctx)).join('');

    /* code blocks — claude.ai renders these as .code-block__code > code, not <pre> */
    if (tag === 'PRE' || node.matches('[class*="code-block"]')) {
      const c = node.querySelector('code') || node;
      const lang = (String(c.className).match(/language-([\w-]+)/) || [, ''])[1];
      return fence(c.textContent, lang);
    }
    if (tag === 'CODE') {
      const lang = (String(node.className).match(/language-([\w-]+)/) || [, ''])[1];
      if (lang || node.textContent.includes('\n')) return fence(node.textContent, lang);
      return '`' + clean(node.textContent) + '`';
    }

    /* honour white-space:pre-wrap so user messages keep their own line breaks */
    let restore = null;
    if (!ctx.pre && /^pre/.test(getComputedStyle(node).whiteSpace)) {
      restore = ctx.pre; ctx.pre = true;
    }
    const done = v => { if (restore !== null) ctx.pre = restore; return v; };

    switch (tag) {
      case 'BR':  return done('\n');
      case 'HR':  return done('\n\n---\n\n');
      case 'P':   return done('\n' + kids().trim() + '\n\n');
      case 'H1': case 'H2': case 'H3': case 'H4': case 'H5': case 'H6':
        return done('\n' + '#'.repeat(+tag[1]) + ' ' + kids().trim() + '\n\n');
      case 'STRONG': case 'B': { const t = kids().trim(); return done(t ? '**' + t + '**' : ''); }
      case 'EM': case 'I':     { const t = kids().trim(); return done(t ? '*' + t + '*' : ''); }
      case 'DEL': case 'S':    { const t = kids().trim(); return done(t ? '~~' + t + '~~' : ''); }
      case 'A': {
        const t = kids().trim(), href = node.getAttribute('href') || '';
        return done(href && t ? '[' + t + '](' + href + ')' : t);
      }
      case 'IMG': {
        const src = node.getAttribute('src') || '';
        const alt = node.getAttribute('alt') || 'image';
        return done('![' + alt + '](' + (src.length > 120 ? src.slice(0, 117) + '...' : src) + ')');
      }
      case 'BLOCKQUOTE':
        return done('\n' + kids().trim().split('\n').map(l => '> ' + l).join('\n') + '\n\n');
      case 'UL': case 'OL': {
        const depth = ctx.list || 0;
        const pad   = '  '.repeat(depth);
        const start = parseInt(node.getAttribute('start') || '1', 10);
        const items = Array.from(node.children).filter(c => c.tagName === 'LI');
        const out = items.map((li, i) => {
          const marker = tag === 'OL' ? (start + i) + '. ' : '- ';
          ctx.list = depth + 1;
          const body = Array.from(li.childNodes).map(n => ser(n, ctx)).join('').trim();
          ctx.list = depth;
          return pad + marker + body.replace(/\n/g, '\n' + pad + '  ');
        }).join('\n');
        return done('\n' + out + '\n\n');
      }
      case 'TABLE': {
        const rows = qsa('tr', node).map(tr =>
          qsa('th,td', tr).map(td => ser(td, ctx).replace(/\n+/g, ' ').replace(/\|/g, '\\|').trim()));
        if (!rows.length) return done('');
        const head = rows[0], body = rows.slice(1);
        return done('\n| ' + head.join(' | ') + ' |\n| ' + head.map(() => '---').join(' | ') + ' |\n' +
                    body.map(r => '| ' + r.join(' | ') + ' |').join('\n') + '\n\n');
      }
      case 'BUTTON': case 'SCRIPT': case 'STYLE': case 'SVG':
        return done('');
      default:
        return done(kids());
    }
  }

  NS.markdown = {
    SKIP,
    isSkippable,
    fence,
    of: node => ser(node, { pre: false, list: 0 })
      .replace(/[ \t]+\n/g, '\n')
      .replace(/\n{3,}/g, '\n\n')
      .trim(),
  };
})();

/* llm-export — provider: Claude (claude.ai)
 *
 * Reads the rendered transcript out of the page. Notable behaviours of the
 * site this has to cope with:
 *   - an owned chat renders its transcript virtualised: only the rows near the
 *     viewport exist in the DOM, keyed by data-rs-index / aria-posinset
 *   - a /share/ snapshot is NOT virtualised, every message is present
 *   - tool and thinking blocks are collapsed; their panels are only mounted
 *     once the pill is clicked
 *   - a /share/ snapshot has connector request/response payloads stripped
 *     server-side, leaving the literal text "Connector data hidden when shared"
 */
(() => {
  'use strict';

  const NS = globalThis.LLMExport;
  const { qsa, clean, sleep, findScroller } = NS.util;
  const md = NS.markdown;

  const MSG_SEL   = '[data-testid="user-message"], [data-testid="assistant-message"]';
  const PROSE_SEL = '[data-perf-reply-text], .standard-markdown, .progressive-markdown, [data-cds="Prose"]';

  const isRowButton = b => !!b.querySelector('[data-testid="tool-row-caret"]');

  /* Tool + thinking blocks */

  /** From a tool row button, climb to the wrapper holding its payload panel. */
  function findPayloadPanel(btn) {
    let n = btn;
    for (let i = 0; i < 7 && n; i++) {
      n = n.parentElement;
      if (!n) break;
      if (qsa('button', n).filter(isRowButton).length > 1) break; // climbed past our own row
      if (n.querySelector('code') || /hidden when shared/i.test(n.textContent || '')) return n;
    }
    return null;
  }

  /** Pull the labelled code blocks (Request / Response / ...) out of a panel. */
  function extractPayloads(panel, btn) {
    const out = [];
    let label = '';
    for (const n of qsa('p, code', panel)) {
      if (btn && btn.contains(n)) continue;
      if (n.tagName === 'P') {
        const t = clean(n.textContent);
        if (t && t.length < 40) label = t;
        continue;
      }
      out.push({
        label: label || 'payload',
        lang:  (String(n.className).match(/language-([\w-]+)/) || [, ''])[1] || '',
        text:  n.textContent.replace(/\s+$/, ''),
      });
      label = '';
    }
    if (!out.length) {
      let t = clean(panel.textContent);
      if (btn) t = t.replace(clean(btn.textContent), '').trim();
      if (t) out.push({ label: 'note', lang: '', text: t });
    }
    return out;
  }

  function parseCall(btn, group) {
    const nameEl = btn.querySelector('[data-cds="ShimmerText"]') || btn;
    const panel  = findPayloadPanel(btn);
    const text   = panel ? panel.textContent : '';
    return {
      name:     clean(nameEl.textContent),
      group,
      expanded: btn.getAttribute('aria-expanded') === 'true',
      hidden:   /hidden when shared/i.test(text),
      payloads: panel ? extractPayloads(panel, btn) : [],
    };
  }

  function parseStatusBlock(container, pill) {
    const label = clean((pill.querySelector('.timeline-status-layer') || pill).textContent);
    const panel = container.querySelector(':scope > [data-cds="Collapsible"]');

    const isThinking = /thought|thinking|reason|ponder|analy[sz]ed|consider/i.test(label) &&
                       !/tool|search|read|fetch|memory|connector/i.test(label);
    if (isThinking) {
      return {
        type: 'thinking',
        label,
        text: panel ? md.of(panel) : '',
        expanded: !!(panel && panel.textContent.trim()),
      };
    }

    const rows  = panel ? qsa('button', panel).filter(isRowButton) : [];
    const calls = rows.map(b => parseCall(b, label));
    if (!calls.length) {
      /* a single-tool pill with no inner row, or a block that never opened */
      const text = panel ? panel.textContent : '';
      calls.push({
        name:     label,
        group:    label,
        expanded: !!(panel && text.trim()),
        hidden:   /hidden when shared/i.test(text),
        payloads: (panel && text.trim()) ? extractPayloads(panel, pill) : [],
      });
    }
    return { type: 'tools', label, calls };
  }

  /** Map of "container element that owns a status pill" -> the pill. */
  function toolGroupContainers(msgEl) {
    const map = new Map();
    for (const pill of qsa('button[data-testid="tool-status-pill"]', msgEl)) {
      let n = pill, container = null;
      for (let i = 0; i < 6 && n && n !== msgEl; i++) {
        n = n.parentElement;
        if (n && n.querySelector(':scope > [data-cds="Collapsible"]')) { container = n; break; }
      }
      map.set(container || pill.parentElement, pill);
    }
    return map;
  }

  /* Messages */
  function collectParts(msgEl, role) {
    if (role === 'user') {
      const text = md.of(msgEl);
      return text ? [{ type: 'text', markdown: text }] : [];
    }

    const groups     = toolGroupContainers(msgEl);
    const groupNodes = Array.from(groups.keys());
    const parts      = [];

    /* Walking in DOM order keeps tool calls interleaved with the prose the
       way they were streamed, rather than lumping them at the top. */
    (function walk(node) {
      if (node.nodeType !== 1 || md.isSkippable(node)) return;
      if (groups.has(node)) { parts.push(parseStatusBlock(node, groups.get(node))); return; }
      if (node.matches(PROSE_SEL) && !groupNodes.some(g => node.contains(g))) {
        const text = md.of(node);
        if (text) parts.push({ type: 'text', markdown: text });
        return;
      }
      for (const child of node.children) walk(child);
    })(msgEl);

    if (!parts.length) {
      const text = md.of(msgEl);
      if (text) parts.push({ type: 'text', markdown: text });
    }
    return parts;
  }

  function nearestTime(el) {
    let n = el;
    for (let i = 0; i < 6 && n; i++) {
      n = n.parentElement;
      if (!n) break;
      if (n.querySelectorAll(MSG_SEL).length > 1) break;  // ancestor now covers other messages
      const t = n.querySelector('time[datetime]');
      if (t) return t.getAttribute('datetime');
    }
    return null;
  }

  /* Provider */
  NS.register({
    id: 'claude',
    label: 'Claude',
    site: 'claude.ai',

    detect: () => /(^|\.)claude\.ai$/.test(location.hostname) ||
                  !!document.querySelector('[data-testid="transcript-list"], [data-testid="assistant-message"]'),

    findRoot: () => document.querySelector('[data-testid="transcript-list"]') ||
                    document.querySelector('[role="feed"]') ||
                    document.body,

    findScroller,

    hasTranscript: root => !!(qsa(MSG_SEL, root).length ||
                              root.querySelector('[data-testid="transcript-sizer"]')),

    isVirtualised: root => !!root.querySelector('[data-testid="transcript-sizer"], [data-rs-index]'),

    /* Click every collapsed tool group, tool row and thinking block open.
       Repeats because opening a group mounts rows that are themselves closed. */
    async expandAll(root, cfg) {
      let clicks = 0;
      for (let round = 0; round < 8; round++) {
        const pills = qsa('button[data-testid="tool-status-pill"][aria-expanded="false"]', root);
        const rows  = qsa('button[aria-expanded="false"]', root).filter(isRowButton);
        const targets = pills.concat(rows);
        if (!targets.length) break;
        for (const t of targets) {
          try { t.click(); clicks++; } catch (_) {}
          await sleep(cfg.clickDelay);
        }
        await sleep(cfg.settle);
      }
      return clicks;
    },

    messages: root => qsa(MSG_SEL, root),

    /* Stable identity for a message, so virtualised rows that unmount and
       remount while we scroll are not counted twice. */
    orderKey(el) {
      const art = el.closest('[role="article"]');
      const pos = art && art.getAttribute('aria-posinset');
      if (pos) return { key: 'p' + pos, order: +pos };
      const row = el.closest('[data-rs-index]');
      if (row) { const i = +row.getAttribute('data-rs-index'); return { key: 'r' + i, order: i }; }
      return null;
    },

    parseMessage(el) {
      const role = el.getAttribute('data-testid') === 'user-message' ? 'user' : 'assistant';
      return { role, time: nearestTime(el), parts: collectParts(el, role) };
    },

    meta(root, messages) {
      const banner   = root.querySelector('[data-cds="Banner"]') ||
                       document.querySelector('[data-cds="Banner"]');
      const sharedBy = (clean(banner && banner.textContent).match(/Shared by ([^.]+)\./) || [, null])[1];
      const isShare  = location.pathname.includes('/share/') || !!sharedBy;

      const titleEl = document.querySelector('[data-testid="chat-title-split"]');
      let title = clean(titleEl && titleEl.textContent) ||
                  document.title.replace(/\s*[-–]\s*Claude\s*$/i, '').trim();
      /* A /share/ page has no chat title — document.title is just "Claude" — so
         fall back to the opening of the first user message. Keep it to one
         clause: this doubles as the default file name. */
      if (!title || /^claude$/i.test(title)) {
        const first = messages.find(m => m.role === 'user');
        const part  = first && first.parts.find(p => p.type === 'text');
        const opening = part ? part.markdown.split('\n')[0].replace(/\s+/g, ' ').trim() : '';
        const clause  = (opening.split(/(?<=[.!?,;:])\s|\s[-–—]\s/)[0] || opening).trim();
        title = clause ? clause.replace(/[.,;:]+$/, '').slice(0, 48).trim() : 'Claude chat';
        if (sharedBy) title = title + ' (shared by ' + sharedBy + ')';
      }
      return { title, sharedBy, kind: isShare ? 'share' : 'chat' };
    },

    /* Shown in the report when tool payloads came back empty. */
    hiddenPayloadNote:
      'claude.ai strips connector request/response payloads out of shared snapshots — ' +
      'tool names survive, arguments and results do not. To capture them, the person who ' +
      'owns the conversation has to run the export on the original chat (claude.ai/chat/...), ' +
      'not on a /share/ link.',
  });
})();

/* llm-export — provider: Gemini (gemini.google.com)
 *
 * Covers both modes the site ships: /app and /spark. They look different but
 * are built from the same Angular components underneath, so one provider
 * reads both.
 *
 * What this has to cope with:
 *   - messages are custom elements, <user-query> and <model-response>, which
 *     sit as siblings in conversation order
 *   - the whole conversation is present in the DOM. A capture of a 40-message
 *     chat spanning 27 screens held all 40, so there is nothing to scroll and
 *     harvest (see the note on orderKey before changing that)
 *   - thinking lives in <remy-processing-state>, collapsed behind a button,
 *     and its text is truncated behind a further "Show all"
 */
(() => {
  'use strict';

  const NS = globalThis.LLMExport;
  const { qsa, clean, sleep, findScroller } = NS.util;
  const md = NS.markdown;

  const MSG_SEL   = 'user-query, model-response';
  const PROSE_SEL = '.markdown-main-panel, .model-response-text .markdown, message-content .markdown';
  const THINK_SEL = 'remy-processing-state';

  const THINK_TOGGLE = 'button[data-test-id="processing-state-container-button"]';
  const SHOW_MORE    = 'button.show-more-button, .show-more-button';

  function parseThinking(el) {
    const header = el.querySelector('[data-test-id="remy-processing-state-text"]');
    const body   = el.querySelector('.processing-state-container-content') || el;
    const toggle = el.querySelector(THINK_TOGGLE);
    return {
      type: 'thinking',
      label: clean(header && header.textContent) || 'Thinking',
      text: md.of(body),
      expanded: !toggle || toggle.getAttribute('aria-expanded') === 'true',
    };
  }

  function collectParts(msgEl, role) {
    if (role === 'user') {
      const body = msgEl.querySelector('.user-query-container') || msgEl;
      const text = md.of(body);
      return text ? [{ type: 'text', markdown: text }] : [];
    }

    const parts = [];
    (function walk(node) {
      if (node.nodeType !== 1 || md.isSkippable(node)) return;
      if (node.matches(THINK_SEL)) { parts.push(parseThinking(node)); return; }
      if (node.matches(PROSE_SEL)) {
        const text = md.of(node);
        if (text) parts.push({ type: 'text', markdown: text });
        return;
      }
      for (const child of node.children) walk(child);
    })(msgEl);

    if (!parts.some(p => p.type === 'text')) {
      const fallback = msgEl.querySelector('.response-content') || msgEl;
      const text = md.of(fallback);
      if (text) parts.push({ type: 'text', markdown: text });
    }
    return parts;
  }

  NS.register({
    id: 'gemini',
    label: 'Gemini',
    site: 'gemini.google.com',

    detect: () => /(^|\.)gemini\.google\.com$/.test(location.hostname) ||
                  !!document.querySelector('user-query, model-response'),

    findRoot: () => document.querySelector('infinite-scroller, .chat-history, chat-window') ||
                    document.body,

    findScroller,

    hasTranscript: root => !!qsa(MSG_SEL, root).length,

    /* Every message is in the page. If a long enough conversation ever proves
       otherwise, give orderKey a stable identity FIRST — turning scrolling on
       without one makes the harvester renumber messages as rows move. */
    isVirtualised: () => false,

    async expandAll(root, cfg) {
      let clicks = 0;
      for (let round = 0; round < 6; round++) {
        const shut = qsa(THINK_TOGGLE + '[aria-expanded="false"]', root);
        /* "Show all" reveals the rest of a thought that is rendered truncated */
        const more = qsa(SHOW_MORE, root).filter(b => /show (all|more)/i.test(b.textContent || ''));
        const targets = shut.concat(more);
        if (!targets.length) break;
        for (const t of targets) {
          try { t.click(); clicks++; } catch (_) {}
          await sleep(cfg.clickDelay);
        }
        await sleep(cfg.settle);
      }
      return clicks;
    },

    messages: root => qsa(MSG_SEL, root),

    /* Nothing on a message is a stable id here, and nothing needs one while
       the transcript is fully rendered: the runner falls back to DOM order. */
    orderKey: () => null,

    parseMessage(el) {
      const role = el.tagName.toLowerCase() === 'user-query' ? 'user' : 'assistant';
      const t = el.querySelector('time[datetime]');
      return {
        role,
        time: t ? t.getAttribute('datetime') : null,
        parts: collectParts(el, role),
      };
    },

    meta(root, messages) {
      const isShare = /\/share\//.test(location.pathname);
      const selected = document.querySelector(
        '.conversation.selected .conversation-title, [data-test-id="conversation-title"]');

      let title = clean(selected && selected.textContent) ||
                  document.title.replace(/\s*[-|]\s*Google Gemini\s*$/i, '')
                                .replace(/\s*[-|]\s*Gemini\s*$/i, '').trim();
      if (!title || /^gemini/i.test(title)) {
        const first = messages.find(m => m.role === 'user');
        const part  = first && first.parts.find(p => p.type === 'text');
        const opening = part ? part.markdown.split('\n')[0].replace(/\s+/g, ' ').trim() : '';
        title = opening.slice(0, 48).trim() || 'Gemini chat';
      }
      return { title, sharedBy: null, kind: isShare ? 'share' : 'chat' };
    },

    hiddenPayloadNote: null,
  });
})();

/* llm-export — provider-agnostic run loop, report builder and saving. */
(() => {
  'use strict';

  const NS = globalThis.LLMExport;
  const { sleep, tryJson, slugify, stamp, fileStamp } = NS.util;

  const DEFAULTS = {
    expand:       true,   // open every tool / thinking block
    scroll:       true,   // walk a virtualised transcript top to bottom
    clickDelay:   70,     // ms between expand clicks
    settle:       260,    // ms for the DOM to settle after a batch
    scrollFactor: 0.6,    // viewport fraction per scroll step
    maxPasses:    600,    // hard stop for the scroll loop
    onProgress:   null,   // fn({phase, note, messages})
  };

  const richness = m => JSON.stringify(m.parts).length;

  /* Tool call index — the flat view that makes a connector easy to audit */
  const pick = (call, re) => {
    const hit = call.payloads.find(p => re.test(p.label));
    return hit ? hit.text : null;
  };

  function buildToolIndex(messages) {
    const calls = [];
    for (const m of messages) {
      for (const part of m.parts) {
        if (part.type !== 'tools') continue;
        for (const c of part.calls) {
          const request  = pick(c, /req|input|param|argument/i);
          const response = pick(c, /resp|result|output|return/i);
          const body = [request, response].concat(c.payloads.map(p => p.text)).join('\n');
          calls.push({
            n: calls.length + 1,
            message: m.index,
            name: c.name,
            group: c.group,
            hidden: c.hidden,
            request,
            response,
            requestJson:  request  ? tryJson(request)  : null,
            responseJson: response ? tryJson(response) : null,
            payloads: c.payloads,
            looksLikeError:
              /"?is_?error"?\s*:\s*true|"error"\s*:|\berror\b|\bfailed\b|not found|denied|unauthori|timeout/i.test(body),
          });
        }
      }
    }
    return calls;
  }

  /* Markdown report */
  function renderMd(d) {
    const L = [];
    L.push('# ' + d.source.title, '');
    L.push('- **Source:** ' + d.source.url);
    L.push('- **Provider:** ' + d.source.provider + (d.source.kind ? ' (' + d.source.kind + ')' : ''));
    L.push('- **Exported:** ' + stamp(d.exportedAt) + ' by ' + d.exporter);
    if (d.source.sharedBy) L.push('- **Shared by:** ' + d.source.sharedBy);
    L.push('- **Messages:** ' + d.stats.messages +
           ' (' + d.stats.user + ' user / ' + d.stats.assistant + ' assistant)');
    L.push('- **Tool calls:** ' + d.stats.toolCalls +
           (d.stats.toolPayloadsHidden ? ' — ' + d.stats.toolPayloadsHidden + ' with payloads hidden' : ''));
    if (d.stats.thinkingBlocks) L.push('- **Thinking blocks:** ' + d.stats.thinkingBlocks);
    L.push('');

    if (d.stats.toolPayloadsHidden && d.notes.hiddenPayloads) {
      L.push('> **Incomplete tool log.** ' + d.notes.hiddenPayloads.replace(/\s+/g, ' '), '');
    }
    L.push('---', '');

    for (const m of d.messages) {
      const who = m.role === 'user' ? 'User' : 'Assistant';
      L.push('## ' + m.index + '. ' + who + (m.time ? '  ·  ' + stamp(m.time) : ''), '');

      for (const part of m.parts) {
        if (part.type === 'text') { L.push(part.markdown, ''); continue; }

        if (part.type === 'thinking') {
          L.push('### [thinking] ' + part.label, '');
          L.push(part.text ? part.text.split('\n').map(l => '> ' + l).join('\n')
                           : '> _(collapsed — not present in this transcript)_', '');
          continue;
        }

        for (const c of part.calls) {
          L.push('### [tool] ' + c.name + (c.group && c.group !== c.name ? '  _(' + c.group + ')_' : ''), '');
          if (c.hidden)             { L.push('_Payload hidden by the site._', ''); continue; }
          if (!c.payloads.length)   { L.push('_No payload captured (block did not open)._', ''); continue; }
          for (const p of c.payloads) {
            L.push('**' + p.label + '**', '');
            L.push('```' + (p.lang || ''), p.text, '```', '');
          }
        }
      }
      L.push('---', '');
    }

    if (d.toolCalls.length) {
      L.push('## Tool call index', '');
      L.push('| # | msg | tool | request | result |');
      L.push('| --- | --- | --- | --- | --- |');
      const cut = s => (s ? s.replace(/\s+/g, ' ').replace(/\|/g, '\\|').slice(0, 70) : '');
      for (const c of d.toolCalls) {
        const result = c.hidden ? 'hidden'
                     : c.looksLikeError ? 'ERROR?'
                     : c.response ? c.response.length + ' chars'
                     : '—';
        L.push('| ' + c.n + ' | ' + c.message + ' | ' + c.name + ' | ' + cut(c.request) + ' | ' + result + ' |');
      }
      L.push('');
    }

    return L.join('\n').replace(/\n{4,}/g, '\n\n\n');
  }

  /* run() */
  async function run(opts) {
    const cfg = Object.assign({}, DEFAULTS, opts || {});
    const provider = (cfg.provider && NS.providers.find(p => p.id === cfg.provider)) || NS.detect();
    if (!provider) throw new Error('No supported chat page detected on ' + location.hostname + '.');

    const root = provider.findRoot();
    if (!provider.hasTranscript(root)) {
      throw new Error('No ' + provider.label + ' transcript on this page. Open a conversation first.');
    }

    const scroller    = provider.findScroller(root);
    const virtualised = provider.isVirtualised(root);
    const startScroll = scroller.scrollTop;

    const seen = new Map();
    let fallbackOrder = 0, expandClicks = 0;

    const say = (phase, note) => {
      if (typeof cfg.onProgress === 'function') {
        try { cfg.onProgress({ phase, note, messages: seen.size }); } catch (_) {}
      }
    };

    function harvest() {
      for (const el of provider.messages(root)) {
        const k     = provider.orderKey(el);
        const key   = k ? k.key   : 'o' + fallbackOrder;
        const order = k ? k.order : fallbackOrder;
        if (!k) fallbackOrder++;
        const msg = provider.parseMessage(el);
        msg.order = order;
        const prev = seen.get(key);
        /* a row can re-render mid-scroll; keep whichever parse saw the most */
        if (!prev || richness(msg) > richness(prev)) seen.set(key, msg);
      }
    }

    say('scanning');

    if (cfg.scroll && virtualised) {
      scroller.scrollTop = 0;
      await sleep(500);
      for (let pass = 0; pass < cfg.maxPasses; pass++) {
        if (cfg.expand) expandClicks += await provider.expandAll(root, cfg);
        fallbackOrder = 0;
        harvest();
        say('scanning', 'pass ' + (pass + 1));
        if (scroller.scrollTop + scroller.clientHeight >= scroller.scrollHeight - 4) break;
        scroller.scrollTop += Math.max(200, scroller.clientHeight * cfg.scrollFactor);
        await sleep(cfg.settle);
      }
      if (cfg.expand) expandClicks += await provider.expandAll(root, cfg);
      fallbackOrder = 0;
      harvest();
    } else {
      if (cfg.expand) expandClicks += await provider.expandAll(root, cfg);
      harvest();
    }

    scroller.scrollTop = startScroll;
    say('building');

    const messages = Array.from(seen.values())
      .sort((a, b) => a.order - b.order)
      .map((m, i) => ({ index: i + 1, role: m.role, time: m.time, parts: m.parts }));

    if (!messages.length) throw new Error('Transcript found but no messages could be read.');

    const meta      = provider.meta(root, messages);
    const toolCalls = buildToolIndex(messages);

    const doc = {
      exportedAt: new Date().toISOString(),
      exporter: 'llm-export v' + NS.version,
      source: {
        url: location.href,
        provider: provider.id,
        site: provider.site,
        title: meta.title,
        kind: meta.kind,
        sharedBy: meta.sharedBy || null,
        virtualised,
      },
      stats: {
        messages: messages.length,
        user: messages.filter(m => m.role === 'user').length,
        assistant: messages.filter(m => m.role === 'assistant').length,
        toolCalls: toolCalls.length,
        toolPayloadsHidden: toolCalls.filter(c => c.hidden).length,
        thinkingBlocks: messages.reduce((n, m) => n + m.parts.filter(p => p.type === 'thinking').length, 0),
        expandClicks,
      },
      notes: {
        hiddenPayloads: toolCalls.some(c => c.hidden) ? (provider.hiddenPayloadNote || null) : null,
      },
      messages,
      toolCalls,
    };

    say('done');
    return {
      doc,
      md: renderMd(doc),
      json: JSON.stringify(doc, null, 2),
      base: provider.id + '-' + (slugify(meta.title) || 'chat') + '-' + fileStamp(),
    };
  }

  /* Saving (page-side blob download; the extension uses chrome.downloads) */
  function download(name, text, type) {
    const url = URL.createObjectURL(new Blob([text], { type }));
    const a = document.createElement('a');
    a.href = url; a.download = name;
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 10000);
  }

  async function save(result, opts) {
    const o = Object.assign({ md: true, json: true }, opts || {});
    if (o.md)   { download(result.base + '.md', result.md, 'text/markdown'); await sleep(700); }
    if (o.json) { download(result.base + '.json', result.json, 'application/json'); }
    return result;
  }

  Object.assign(NS, { DEFAULTS, run, save, download, renderMd, buildToolIndex });
})();

/* llm-export — page capture, for adding support for a new chat site.
 *
 * Dumps the page HTML plus a summary of the structures a provider hooks into.
 * Used by the popup's "Capture this page" button, and available in the console
 * bundle as LLMExport.captureAndSave().
 *
 * Expand a tool call and a thinking block by hand before capturing: those
 * panels usually do not exist in the DOM until clicked, so a collapsed dump
 * cannot show what a payload looks like.
 */
(() => {
  'use strict';

  const NS = globalThis.LLMExport;

  /* The most common values of an attribute, which is usually enough to spot
     the site's own naming scheme for messages, roles and tool blocks. */
  function attrValues(attr, limit = 60) {
    const counts = {};
    for (const el of document.querySelectorAll('[' + attr + ']')) {
      const v = el.getAttribute(attr);
      if (v) counts[v] = (counts[v] || 0) + 1;
    }
    return Object.fromEntries(Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, limit));
  }

  /* Whatever scrolls is a candidate for the transcript container. */
  function scrollers() {
    const out = [];
    for (const el of document.querySelectorAll('*')) {
      const st = getComputedStyle(el);
      if (/(auto|scroll)/.test(st.overflowY) && el.scrollHeight > el.clientHeight + 200) {
        out.push({
          tag: el.tagName.toLowerCase(),
          id: el.id || null,
          testid: el.getAttribute('data-testid') || null,
          cls: String(el.className || '').slice(0, 120),
          scrollHeight: el.scrollHeight,
          clientHeight: el.clientHeight,
          children: el.children.length,
        });
      }
    }
    return out;
  }

  /* Count the nodes that look like they hold one message. Sites label these
     very differently — custom elements on Gemini and AI Studio, data-turn on
     ChatGPT, data-testid on Claude, plain classes on DeepSeek — so cast wide
     and report what each pattern found rather than guessing a single answer. */
  function messageNodeCounts() {
    const probes = {
      'aria posinset':      '[aria-posinset]',
      'role=article':       '[role="article"], article',
      'data-turn':          '[data-turn], [data-turn-id], [data-turn-role]',
      'author role':        '[data-message-author-role], [data-message-id]',
      'custom elements':    'user-query, model-response, ms-chat-turn',
      'testid message':     '[data-testid*="message" i], [data-testid*="turn" i], [data-testid*="conversation-turn" i]',
      'class message':      '[class*="message" i]:not([class*="messages" i]), [class*="chat-turn" i]',
    };
    const out = {};
    for (const [label, sel] of Object.entries(probes)) {
      try { out[label] = document.querySelectorAll(sel).length; } catch (_) { out[label] = null; }
    }
    return out;
  }

  function capture() {
    const posinset = document.querySelectorAll('[aria-posinset]').length;
    const setsize  = document.querySelector('[aria-setsize]');
    const total    = setsize ? +setsize.getAttribute('aria-setsize') : null;

    /* How far the page scrolls, in viewports. A transcript that scrolls for
       twenty screens but holds four message nodes is virtualised: most of the
       conversation is not in the page, and an exporter that reads the DOM once
       would quietly keep only what was on screen. */
    const tall   = scrollers();
    const screens = tall.reduce((best, s) =>
      Math.max(best, s.clientHeight ? s.scrollHeight / s.clientHeight : 0), 0);
    const nodes  = messageNodeCounts();
    const mostNodes = Math.max(0, ...Object.values(nodes).filter(n => typeof n === 'number'));

    return {
      capturedAt: new Date().toISOString(),
      exporter: 'llm-export v' + NS.version,
      url: location.href,
      host: location.hostname,
      path: location.pathname,
      title: document.title,
      userAgent: navigator.userAgent,

      hints: {
        dataTestIds: attrValues('data-testid'),
        dataCds: attrValues('data-cds'),
        roles: attrValues('role', 30),
        scrollers: tall,
        screensOfScroll: Math.round(screens * 10) / 10,
        messageNodes: nodes,
        articleNodes: nodes['role=article'],
        posinsetNodes: posinset,
        ariaSetsize: total,
        /* Two independent signals. aria-setsize is definitive where a site sets
           it, but most do not; otherwise infer from scroll length against how
           many message nodes are actually present. */
        looksVirtualised: (total && total > posinset) ? true
                        : (screens >= 4 && mostNodes && mostNodes < screens) ? true
                        : (screens >= 4 && mostNodes >= screens) ? false
                        : null,   // too short to tell
        expandableButtons: document.querySelectorAll('[aria-expanded]').length,
        collapsedButtons: document.querySelectorAll('[aria-expanded="false"]').length,
        codeBlocks: document.querySelectorAll('pre, code').length,
        timeNodes: document.querySelectorAll('time[datetime]').length,
      },

      html: document.documentElement.outerHTML,
    };
  }

  function captureName(dump) {
    return 'capture-' + (dump.host || 'page').replace(/[^a-z0-9]+/gi, '-') + '-' +
           NS.util.fileStamp() + '.json';
  }

  async function captureAndSave() {
    const dump = capture();
    const name = captureName(dump);
    NS.download(name, JSON.stringify(dump, null, 2), 'application/json');
    console.log('%c[llm-export] captured ' + name, 'color:#c96442;font-weight:bold');
    const v = dump.hints.looksVirtualised;
    console.log('  html: ' + (dump.html.length / 1024).toFixed(0) + ' KB' +
                ' | ' + dump.hints.screensOfScroll + ' screens of scroll' +
                ' | virtualised: ' + (v === null ? 'too short to tell' : v) +
                ' | collapsed blocks: ' + dump.hints.collapsedButtons);
    console.table(dump.hints.messageNodes);
    return dump;
  }

  Object.assign(NS, { capture, captureName, captureAndSave });
})();

/* llm-export — extension entry point.
 * Appended to the core by build.mjs to produce extension/content.js.
 * Runs in the page as a content script; the service worker does the saving.
 */
(() => {
  'use strict';

  if (globalThis.__llmExportBridge) return;   // re-injected on every popup / menu click
  globalThis.__llmExportBridge = true;

  const post = m => { try { chrome.runtime.sendMessage(m); } catch (_) {} };

  const sanitize = s => String(s || '')
    .replace(/[\\/:*?"<>|\u0000-\u001f\uE000-\uF8FF]/g, '-')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^\.+|\.+$/g, '')
    .slice(0, 80) || 'chat';

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (!msg || msg.type !== 'llm-export:run') return;

    (async () => {
      try {
        const o = msg.opts || {};
        const res = await globalThis.LLMExport.run({
          expand: o.expand !== false,
          onProgress: p => post({
            type: 'llm-export:progress', phase: p.phase, note: p.note, messages: p.messages,
          }),
        });

        /* Ask for a file name, defaulting to the chat's own title. */
        let base = res.base;
        if (o.askName) {
          const answer = window.prompt('Save this export as:', sanitize(res.doc.source.title));
          if (answer === null) { post({ type: 'llm-export:cancelled' }); try { sendResponse({ ok: false, cancelled: true }); } catch (_) {} return; }
          base = sanitize(answer) || res.base;
        }

        const files = [];
        if (o.md   !== false) files.push({ name: base + '.md',   text: res.md,   mime: 'text/markdown' });
        if (o.json !== false) files.push({ name: base + '.json', text: res.json, mime: 'application/json' });

        post({
          type: 'llm-export:result',
          files,
          base,
          stats: res.doc.stats,
          source: res.doc.source,
          notes: res.doc.notes,
          md: res.md.length < 1200000 ? res.md : null,
        });
        try { sendResponse({ ok: true, stats: res.doc.stats }); } catch (_) {}
      } catch (err) {
        const message = String((err && err.message) || err);
        post({ type: 'llm-export:error', error: message });
        try { sendResponse({ ok: false, error: message }); } catch (_) {}
      }
    })();

    return true;   // keep the channel open for the async reply
  });

  /* Dump this page for someone adding support for a new site. */
  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (!msg || msg.type !== 'llm-export:capture') return;
    try {
      const dump = globalThis.LLMExport.capture();
      post({
        type: 'llm-export:result',
        kind: 'capture',
        files: [{
          name: globalThis.LLMExport.captureName(dump),
          text: JSON.stringify(dump, null, 2),
          mime: 'application/json',
        }],
        source: { url: dump.url, provider: 'capture', title: dump.title, kind: 'capture' },
        stats: { host: dump.host, kb: Math.round(dump.html.length / 1024), hints: dump.hints },
        base: globalThis.LLMExport.captureName(dump).replace(/\.json$/, ''),
      });
      sendResponse({ ok: true, host: dump.host, kb: Math.round(dump.html.length / 1024),
                     looksVirtualised: dump.hints.looksVirtualised,
                     collapsed: dump.hints.collapsedButtons });
    } catch (err) {
      const message = String((err && err.message) || err);
      post({ type: 'llm-export:error', error: message });
      try { sendResponse({ ok: false, error: message }); } catch (_) {}
    }
    return true;
  });

  /* Let the popup know which provider claimed this page. */
  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (!msg || msg.type !== 'llm-export:detect') return;
    let info = { ok: false };
    try {
      const p = globalThis.LLMExport.detect();
      if (p) {
        const root = p.findRoot();
        info = {
          ok: true,
          provider: p.id,
          label: p.label,
          site: p.site,
          hasTranscript: p.hasTranscript(root),
          messages: p.messages(root).length,
          kind: location.pathname.includes('/share/') ? 'share' : 'chat',
        };
      }
    } catch (err) {
      info = { ok: false, error: String((err && err.message) || err) };
    }
    sendResponse(info);
    return true;
  });

  post({ type: 'llm-export:ready' });
})();
