/* llm-export v1.2.0 — supported sites
 * GENERATED by build.mjs from src/. Do not edit this file; edit src/ and rebuild.
 */
export const SITES = [
  {
    "id": "claude",
    "label": "note",
    "site": "claude.ai"
  },
  {
    "id": "gemini",
    "label": "Gemini",
    "site": "gemini.google.com"
  }
];

export const URL_PATTERNS = [
  "https://claude.ai/*",
  "https://*.claude.ai/*",
  "https://gemini.google.com/*",
  "https://*.gemini.google.com/*"
];
