/* llm-export v1.1.0 — supported sites
 * GENERATED by build.mjs from src/. Do not edit this file; edit src/ and rebuild.
 */
export const SITES = [
  {
    "id": "claude",
    "label": "note",
    "site": "claude.ai"
  }
];

export const URL_PATTERNS = [
  "https://claude.ai/*",
  "https://*.claude.ai/*"
];
