#!/usr/bin/env node
/* Builds llm-export from src/.
 *
 *   ../builds/llm-export-console.js        paste-into-F12 console script
 *   extension/content.js                   extension content script (kept in-tree
 *                                          so extension/ stays loadable unpacked)
 *   extension/sites.js                     provider url patterns, for the context menu
 *   ../builds/llm-export-extension-vX.zip  packed extension   (node build.mjs --zip)
 *
 * No bundler: src files are plain IIFEs concatenated in order, each hanging
 * itself off globalThis.LLMExport.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, rmSync, cpSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const here   = dirname(fileURLToPath(import.meta.url));
const srcDir = resolve(here, 'src');
const extDir = resolve(here, 'extension');
const builds = resolve(here, '../builds');

const providerFiles = readdirSync(join(srcDir, 'providers')).filter(f => f.endsWith('.js')).sort();

const ORDER = [
  'runtime.js',
  'markdown.js',
  ...providerFiles.map(f => 'providers/' + f),
  'runner.js',
];

const core = ORDER.map(f => readFileSync(join(srcDir, f), 'utf8')).join('\n');
const version = (core.match(/NS\.version\s*=\s*'([^']+)'/) || [, '0.0.0'])[1];

const header = what =>
  `/* llm-export v${version} — ${what}\n` +
  ` * GENERATED by build.mjs from src/. Do not edit this file; edit src/ and rebuild.\n` +
  ` */\n`;

/* ------------------------------------------------------------------ *
 * Provider site list -> extension/sites.js
 * ------------------------------------------------------------------ */
const sites = providerFiles.map(f => {
  const text = readFileSync(join(srcDir, 'providers', f), 'utf8');
  return {
    id:   (text.match(/\bid:\s*'([^']+)'/)   || [, f.replace(/\.js$/, '')])[1],
    label:(text.match(/\blabel:\s*'([^']+)'/) || [, ''])[1],
    site: (text.match(/\bsite:\s*'([^']+)'/)  || [, ''])[1],
  };
}).filter(p => p.site);

const patterns = sites.flatMap(p => [`https://${p.site}/*`, `https://*.${p.site}/*`]);

writeFileSync(join(extDir, 'sites.js'),
  header('supported sites') +
  'export const SITES = ' + JSON.stringify(sites, null, 2) + ';\n\n' +
  'export const URL_PATTERNS = ' + JSON.stringify(patterns, null, 2) + ';\n', 'utf8');

/* ------------------------------------------------------------------ *
 * Bundles
 * ------------------------------------------------------------------ */
mkdirSync(builds, { recursive: true });

const consoleJs = header('console script')            + core + '\n' + readFileSync(join(srcDir, 'entries/console.js'), 'utf8');
const contentJs = header('extension content script')  + core + '\n' + readFileSync(join(srcDir, 'entries/extension.js'), 'utf8');

writeFileSync(join(builds, 'llm-export-console.js'), consoleJs, 'utf8');
writeFileSync(join(extDir, 'content.js'), contentJs, 'utf8');

/* what version is in this folder, readable without opening the manifest */
writeFileSync(join(extDir, 'VERSION.txt'),
  [
    `llm-export ${version}`,
    '',
    'To update: "Extract here" the new zip into the same place as last time. It',
    'always unpacks to a folder called llm-export-extension, whatever the zip is',
    'named, so it overwrites this folder rather than making a new one. Then press',
    "Reload on the extension's card in chrome://extensions.",
    '',
    'Because the folder path never changes, the extension never needs adding again.',
    '',
    'Latest release: https://github.com/QueenRose4444/llm-export/releases/latest',
    '',
  ].join('\n'), 'utf8');

/* keep the manifest version in step with src/runtime.js */
const manifestPath = join(extDir, 'manifest.json');
try {
  const m = JSON.parse(readFileSync(manifestPath, 'utf8'));
  if (m.version !== version) {
    m.version = version;
    writeFileSync(manifestPath, JSON.stringify(m, null, 2) + '\n', 'utf8');
    console.log('manifest version -> ' + version);
  }
} catch (_) { /* manifest not created yet */ }

console.log(`llm-export v${version}`);
console.log('  providers:                       ' + sites.map(s => s.id + ' (' + s.site + ')').join(', '));
console.log('  ../builds/llm-export-console.js  ' + consoleJs.length + ' bytes');
console.log('  extension/content.js             ' + contentJs.length + ' bytes');
console.log('  extension/sites.js               ' + patterns.length + ' url patterns');

/* ------------------------------------------------------------------ *
 * --zip: pack the extension for a release
 * ------------------------------------------------------------------ */
if (process.argv.includes('--zip')) {
  /* The zip FILE carries the version, so releases are tellable apart in a
     downloads folder. The folder INSIDE it does not: an unpacked extension is
     bound to its folder, so a versioned folder name forces the user to add the
     extension again on every update. Taking the folder name from the zip's
     content rather than its filename also survives Chrome's "(1)" suffix on a
     re-download — "Extract here" always lands on the same path, and updating is
     Extract → Reload. The version is in VERSION.txt and the manifest. */
  const stage = join(builds, '.stage');
  const inner = join(stage, 'llm-export-extension');
  const zip   = join(builds, `llm-export-extension-v${version}.zip`);
  rmSync(stage, { recursive: true, force: true });
  rmSync(zip, { force: true });
  mkdirSync(inner, { recursive: true });
  cpSync(extDir, inner, { recursive: true });
  try {
    execFileSync('powershell.exe', ['-NoProfile', '-Command',
      `Compress-Archive -Path '${inner}' -DestinationPath '${zip}' -Force`], { stdio: 'inherit' });
    console.log('  packed llm-export-extension-v' + version + '.zip' +
                ' (' + statSync(zip).size + ' bytes, unzips to llm-export-extension/)');
  } catch (err) {
    console.error('  zip failed:', err.message);
  } finally {
    rmSync(stage, { recursive: true, force: true });
  }
}
